spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/happycoding?useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&serverTimezone=GMT%2B8
    username : happycoder
    password : 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  activiti:
    #Activiti记录历史任务数据级别none, acitivity, audit, all，full是最全的，方便日后查询使用
    history-level: full
    #创建数据库历史数据表
    db-history-used: true
    #建表规则
    #flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。
    #true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
    #create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
    #drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: false
  main:
    log-startup-info: false